services:
  db:
    image: postgres:12.1-alpine
    # restart: always
    volumes:
      - postgres_data_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=diana123
      - POSTGRES_DB=postgres

  user_service:
    build: ./user-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    # restart: always
    depends_on:
      - db
    volumes:
      - ./user-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://postgres:diana123@db/postgres

  product_service:
    build: ./product-service
    # restart: always
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db
    volumes:
      - ./product-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://postgres:diana123@db/postgres

  order_service:
    build: ./order-service
    # restart: always
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db
    volumes:
      - ./order-service/:/app/
    ports:
      - 8003:8000
    environment:
      - DATABASE_URI=postgresql://postgres:diana123@db/postgres
      - PRODUCT_SERVICE_HOST_URL=http://product_service:8000/api/v1/products/
      - USER_SERVICE_HOST_URL=http://user_service:8000/api/v1/users/

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_service
      - product_service
      - order_service

volumes:
  postgres_data_db: